type LayoutProps = {
    title: string;
    language: string;
    children: string;
    pathPrefix?: string; // relative path to root, e.g. "../../../"
    microblogEndpoint?: string | null;
    microblogToken?: string | null;
    hasMicroblog?: boolean;
};

const searchIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>`;
const postIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>`;

export const Layout = ({ title, language, children, pathPrefix = "", microblogEndpoint = null, microblogToken = null, hasMicroblog = false }: LayoutProps): string => {
    const buildTime = new Date().toISOString();
    return (
        <html lang={language}>
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>{title}</title>
                <link rel="icon" type="image/svg+xml" href={`${pathPrefix}favicon.svg`} />
                <link rel="apple-touch-icon" sizes="180x180" href={`${pathPrefix}apple-touch-icon.png`} />
                <link rel="icon" type="image/png" sizes="32x32" href={`${pathPrefix}favicon-32x32.png`} />
                <link rel="icon" type="image/png" sizes="16x16" href={`${pathPrefix}favicon-16x16.png`} />
                <link rel="stylesheet" href={`${pathPrefix}assets/style.css`} />
                <link href={`${pathPrefix}pagefind/pagefind-ui.css`} rel="stylesheet" />
            </head>
            <body data-build-time={buildTime} data-microblog-endpoint={microblogEndpoint || undefined} data-microblog-token={microblogToken || undefined}>
                <header class="site-header">
                    <nav>
                        <a href={`${pathPrefix}index.html`} class="site-title">chronixd</a>
                    </nav>
                </header>
                <main data-pagefind-body="" dangerouslySetInnerHTML={{ __html: children }}>
                </main>
                <div id="search-overlay" class="search-overlay" hidden="">
                    <div class="search-overlay-inner">
                        <div id="search"></div>
                        <button id="search-close" class="search-close" type="button">Close</button>
                    </div>
                </div>
                <div class="fab-group">
                    <button type="button" id="search-toggle" class="fab" aria-label="Search">
                        <span dangerouslySetInnerHTML={{ __html: searchIcon }}></span>
                    </button>
                    <a href={`${pathPrefix}post.html`} class="fab fab-primary" aria-label="Post">
                        <span dangerouslySetInnerHTML={{ __html: postIcon }}></span>
                    </a>
                </div>
                <footer class="site-footer">
                    <p>Generated by chronixd</p>
                </footer>
                <script src={`${pathPrefix}pagefind/pagefind-ui.js`} type="text/javascript"></script>
                <script dangerouslySetInnerHTML={{ __html: `
                    window.addEventListener('DOMContentLoaded', function() {
                        if (typeof PagefindUI !== 'undefined') {
                            new PagefindUI({ element: "#search", showSubResults: true, sort: { date: "desc" } });
                        }
                        var overlay = document.getElementById('search-overlay');
                        var toggle = document.getElementById('search-toggle');
                        var close = document.getElementById('search-close');
                        if (toggle && overlay) {
                            toggle.addEventListener('click', function() {
                                overlay.hidden = !overlay.hidden;
                                if (!overlay.hidden) {
                                    var input = overlay.querySelector('.pagefind-ui__search-input');
                                    if (input) input.focus();
                                }
                            });
                        }
                        if (close && overlay) {
                            close.addEventListener('click', function() { overlay.hidden = true; });
                        }
                        if (overlay) {
                            overlay.addEventListener('click', function(e) {
                                if (e.target === overlay) overlay.hidden = true;
                            });
                        }
                        document.addEventListener('keydown', function(e) {
                            if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;
                            if (e.key === 'n') {
                                var postLink = document.querySelector('.fab-primary');
                                if (postLink) location.href = postLink.href;
                            }
                            if (e.key === 'Escape' && overlay && !overlay.hidden) {
                                overlay.hidden = true;
                            }
                        });
                    });
                ` }}></script>
                {microblogToken ? <script dangerouslySetInnerHTML={{ __html: `
                    (function(){
                        var t="${microblogToken}";
                        document.querySelectorAll("img[data-auth-src]").forEach(function(img){
                            fetch(img.dataset.authSrc,{headers:{Authorization:"Bearer "+t}})
                                .then(function(r){if(!r.ok)throw r;return r.blob()})
                                .then(function(b){img.src=URL.createObjectURL(b)})
                                .catch(function(){});
                        });
                    })();
                ` }}></script> : ""}
                <script dangerouslySetInnerHTML={{ __html: `
                    (function(){
                        var fmt=new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",hourCycle:"h23"});
                        var now=Date.now();
                        var DAY=864e5;
                        var rtf;
                        try{rtf=new Intl.RelativeTimeFormat(undefined,{numeric:"auto"})}catch(e){}
                        document.querySelectorAll("time.entry-time[datetime]").forEach(function(el){
                            var dt=new Date(el.getAttribute("datetime"));
                            if(isNaN(dt))return;
                            var end=el.dataset.end?new Date(el.dataset.end):null;
                            if(end&&!isNaN(end)){
                                el.textContent=fmt.format(dt)+" - "+fmt.format(end);
                                return;
                            }
                            var diff=now-dt.getTime();
                            if(rtf&&diff>=0&&diff<DAY){
                                var m=Math.floor(diff/6e4);
                                var h=Math.floor(diff/36e5);
                                el.textContent=m<1?rtf.format(0,"minute"):h<1?rtf.format(-m,"minute"):rtf.format(-h,"hour");
                            }else{
                                el.textContent=fmt.format(dt);
                            }
                        });
                    })();
                ` }}></script>
                <script src={`${pathPrefix}assets/post-client.js`} type="module"></script>
                <script src={`${pathPrefix}assets/location-map.js`} defer></script>
            </body>
        </html>
    );
};
