type LayoutProps = {
    title: string;
    language: string;
    children: string;
    pathPrefix?: string; // relative path to root, e.g. "../../../"
    microblogToken?: string | null;
};

export const Layout = ({ title, language, children, pathPrefix = "", microblogToken = null }: LayoutProps): string => {
    return (
        <html lang={language}>
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>{title}</title>
                <link rel="stylesheet" href={`${pathPrefix}assets/style.css`} />
                <link href={`${pathPrefix}pagefind/pagefind-ui.css`} rel="stylesheet" />
            </head>
            <body>
                <header class="site-header">
                    <nav>
                        <a href={`${pathPrefix}index.html`} class="site-title">chronixd</a>
                    </nav>
                    <div id="search"></div>
                </header>
                <main data-pagefind-body="" dangerouslySetInnerHTML={{ __html: children }}>
                </main>
                <footer class="site-footer">
                    <p>Generated by chronixd</p>
                </footer>
                <script src={`${pathPrefix}pagefind/pagefind-ui.js`} type="text/javascript"></script>
                <script dangerouslySetInnerHTML={{ __html: `
                    window.addEventListener('DOMContentLoaded', function() {
                        if (typeof PagefindUI !== 'undefined') {
                            new PagefindUI({ element: "#search", showSubResults: true, sort: { date: "desc" } });
                        }
                    });
                ` }}></script>
                {microblogToken ? <script dangerouslySetInnerHTML={{ __html: `
                    (function(){
                        var t="${microblogToken}";
                        document.querySelectorAll("img[data-auth-src]").forEach(function(img){
                            fetch(img.dataset.authSrc,{headers:{Authorization:"Bearer "+t}})
                                .then(function(r){if(!r.ok)throw r;return r.blob()})
                                .then(function(b){img.src=URL.createObjectURL(b)})
                                .catch(function(){});
                        });
                    })();
                ` }}></script> : ""}
                <script src={`${pathPrefix}assets/post-client.js`} type="module"></script>
                <script src={`${pathPrefix}assets/location-map.js`} defer></script>
            </body>
        </html>
    );
};
