import sharp from "sharp";
import * as fs from "fs/promises";
import * as path from "path";

const SVG_PATH = path.resolve("src/generate/assets/favicon.svg");
const OUTPUT_PATH = path.resolve("src/generate/assets/favicon-data.ts");

const svgBuffer = await fs.readFile(SVG_PATH);

const png180 = await sharp(svgBuffer).resize(180, 180).png().toBuffer();
const png32 = await sharp(svgBuffer).resize(32, 32).png().toBuffer();
const png16 = await sharp(svgBuffer).resize(16, 16).png().toBuffer();

const output = `// AUTO-GENERATED by scripts/generate-favicon-data.ts -- do not edit
export const faviconPng180 = "${png180.toString("base64")}";
export const faviconPng32 = "${png32.toString("base64")}";
export const faviconPng16 = "${png16.toString("base64")}";
`;

await fs.writeFile(OUTPUT_PATH, output, "utf-8");
/* eslint-disable no-console */
console.log("Generated favicon-data.ts");
console.log(`  apple-touch-icon (180x180): ${png180.length} bytes`);
console.log(`  favicon-32x32: ${png32.length} bytes`);
console.log(`  favicon-16x16: ${png16.length} bytes`);
